export const CITIES = [
  "Tel Aviv",
  "Jérusalem",
  "Haïfa",
  "Rishon LeZion",
  "Petah Tikva",
  "Beer Sheva",
  "Netanya",
  "Ashdod",
  "Holon",
  "Bnei Brak",
  "Bat Yam",
  "Ramat Gan",
  "Rehovot",
  "Ashkelon",
  "Herzliya",
  "Kfar Saba",
  "Ra'anana",
  "Hadera",
  "Modiin",
  "Lod",
  "Nazareth",
  "Tiberias",
  "Eilat",
  "Dimona",
  "Acre",
  "Safed",
  "Kiryat Shmona",
  "Nahariya",
  "Givatayim",
  "Ramat Hasharon",
];

export const SERVICES = [
  "Coiffeur",
  "Esthéticienne",
  "Coach sportif",
  "Avocat",
  "Comptable",
  "Médecin",
  "Psychologue",
  "Dentiste",
  "Kinésithérapeute",
  "Ostéopathe",
  "Naturopathe",
  "Nutritionniste",
  "Professeur particulier",
  "Babysitter",
  "Femme de ménage",
  "Plombier",
  "Électricien",
  "Peintre",
  "Menuisier",
  "Jardinier",
  "Photographe",
  "Vidéaste",
  "Graphiste",
  "Développeur web",
  "Traducteur",
  "Massage",
  "Yoga",
  "Pilates",
  "Cours de cuisine",
  "Cours de langues",
  "Architecte",
  "Designer d'intérieur",
  "Agent immobilier",
  "Conseiller financier",
  "Autre",
];

export const SERVICE_SUBCATEGORIES: Record<string, string[]> = {
  "Coiffeur": [
    "Homme",
    "Femme",
    "Enfant",
    "Mariée",
    "Coloration",
    "Mèches",
    "Lissage",
    "Permanente",
    "Barbe",
    "Coupe tendance",
  ],
  "Esthéticienne": [
    "Soin du visage",
    "Épilation",
    "Manucure",
    "Pédicure",
    "Maquillage",
    "Pose d'ongles",
    "Microblading",
    "Lash lift",
    "Soin du corps",
    "Massage relaxant",
  ],
  "Coach sportif": [
    "Perte de poids",
    "Prise de masse",
    "Cardio",
    "Musculation",
    "Yoga",
    "Pilates",
    "CrossFit",
    "Préparation physique",
    "Rééducation",
    "Sport en groupe",
  ],
  "Médecin": [
    "Médecin généraliste",
    "Pédiatre",
    "Gynécologue",
    "Cardiologue",
    "Dermatologue",
    "Ophtalmologue",
    "ORL",
    "Orthopédiste",
    "Neurologue",
    "Psychiatre",
  ],
  "Dentiste": [
    "Soins dentaires",
    "Blanchiment",
    "Orthodontie",
    "Implant",
    "Prothèse",
    "Parodontologie",
    "Endodontie",
    "Chirurgie buccale",
  ],
  "Massage": [
    "Massage relaxant",
    "Massage thérapeutique",
    "Massage sportif",
    "Massage aux pierres chaudes",
    "Réflexologie",
    "Shiatsu",
    "Massage thaï",
    "Massage prénatal",
  ],
  "Photographe": [
    "Mariage",
    "Portrait",
    "Famille",
    "Grossesse",
    "Événement",
    "Produit",
    "Immobilier",
    "Corporate",
  ],
  "Traducteur": [
    "Français-Hébreu",
    "Français-Anglais",
    "Hébreu-Anglais",
    "Arabe-Français",
    "Russe-Français",
    "Traduction officielle",
    "Interprétation",
  ],
  "Cours de langues": [
    "Hébreu",
    "Français",
    "Anglais",
    "Arabe",
    "Russe",
    "Espagnol",
    "Préparation examens",
    "Conversation",
  ],
  "Professeur particulier": [
    "Mathématiques",
    "Physique",
    "Chimie",
    "Biologie",
    "Français",
    "Anglais",
    "Hébreu",
    "Histoire",
    "Économie",
    "Informatique",
  ],
  "Avocat": [
    "Droit civil",
    "Droit pénal",
    "Droit du travail",
    "Droit immobilier",
    "Droit de la famille",
    "Droit commercial",
    "Immigration",
    "Consultation juridique",
  ],
  "Comptable": [
    "Comptabilité générale",
    "Déclarations fiscales",
    "Conseil fiscal",
    "Audit",
    "Gestion de paie",
    "Création d'entreprise",
  ],
  "Psychologue": [
    "Thérapie individuelle",
    "Thérapie de couple",
    "Thérapie familiale",
    "Thérapie enfants",
    "Gestion du stress",
    "Dépression",
    "Anxiété",
    "Troubles alimentaires",
  ],
  "Kinésithérapeute": [
    "Rééducation",
    "Massage thérapeutique",
    "Sport",
    "Posture",
    "Douleurs chroniques",
    "Kinésithérapie respiratoire",
  ],
  "Ostéopathe": [
    "Ostéopathie structurelle",
    "Ostéopathie viscérale",
    "Ostéopathie crânienne",
    "Sport",
    "Grossesse",
    "Enfants",
  ],
  "Naturopathe": [
    "Nutrition",
    "Phytothérapie",
    "Aromathérapie",
    "Bien-être",
    "Détox",
    "Consultation",
  ],
  "Nutritionniste": [
    "Perte de poids",
    "Prise de poids",
    "Nutrition sportive",
    "Allergies alimentaires",
    "Diabète",
    "Végétarien/Végan",
  ],
  "Plombier": [
    "Réparation",
    "Installation",
    "Dépannage urgence",
    "Chauffe-eau",
    "Robinetterie",
    "Canalisation",
  ],
  "Électricien": [
    "Installation",
    "Réparation",
    "Dépannage urgence",
    "Éclairage",
    "Tableau électrique",
    "Sécurité",
  ],
  "Peintre": [
    "Peinture intérieure",
    "Peinture extérieure",
    "Papier peint",
    "Faux plafond",
    "Décoration",
    "Rénovation",
  ],
  "Menuisier": [
    "Mobilier sur mesure",
    "Étagères",
    "Placards",
    "Rénovation",
    "Parquet",
    "Portes/Fenêtres",
  ],
  "Jardinier": [
    "Entretien",
    "Aménagement",
    "Taille",
    "Plantation",
    "Irrigation",
    "Paysagiste",
  ],
  "Vidéaste": [
    "Mariage",
    "Événement",
    "Corporate",
    "Publicité",
    "Documentaire",
    "Montage",
  ],
  "Graphiste": [
    "Logo",
    "Identité visuelle",
    "Affiches",
    "Brochures",
    "Web design",
    "Packaging",
  ],
  "Développeur web": [
    "Site web",
    "Application mobile",
    "E-commerce",
    "WordPress",
    "Maintenance",
    "Consultation",
  ],
  "Yoga": [
    "Hatha Yoga",
    "Vinyasa",
    "Ashtanga",
    "Yin Yoga",
    "Yoga prénatal",
    "Méditation",
  ],
  "Pilates": [
    "Pilates classique",
    "Pilates sur machine",
    "Pilates prénatal",
    "Rééducation",
    "Groupe",
    "Individuel",
  ],
  "Cours de cuisine": [
    "Cuisine française",
    "Cuisine israélienne",
    "Pâtisserie",
    "Cuisine végétarienne",
    "Cuisine pour enfants",
    "Atelier groupe",
  ],
  "Architecte": [
    "Architecture résidentielle",
    "Architecture commerciale",
    "Rénovation",
    "Permis de construire",
    "Design intérieur",
    "Consultation",
  ],
  "Designer d'intérieur": [
    "Décoration",
    "Aménagement",
    "Rénovation",
    "Consultation",
    "Achat meubles",
    "Style moderne",
  ],
  "Agent immobilier": [
    "Vente",
    "Location",
    "Achat",
    "Estimation",
    "Gestion locative",
    "Consultation",
  ],
  "Conseiller financier": [
    "Planification financière",
    "Investissement",
    "Retraite",
    "Assurance",
    "Crédit",
    "Consultation",
  ],
  "Babysitter": [
    "Garde régulière",
    "Garde ponctuelle",
    "Soirée",
    "Week-end",
    "Vacances",
    "Aide aux devoirs",
  ],
  "Femme de ménage": [
    "Ménage régulier",
    "Ménage ponctuel",
    "Nettoyage profond",
    "Repassage",
    "Organisation",
    "Bureaux",
  ],
};

